# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0011_createapplication_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth0_type', models.CharField(max_length=10)),
                ('eth1_type', models.CharField(max_length=10)),
                ('eth2_type', models.CharField(max_length=10)),
                ('eth3_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('machines', models.TextField(max_length=500)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.Host')),
            ],
        ),
        migrations.AddField(
            model_name='netinterface',
            name='eth0_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eth0_vms', to='Web.Network'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='eth1_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eth1_vms', to='Web.Network'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='eth2_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eth2_vms', to='Web.Network'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='eth3_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eth3_vms', to='Web.Network'),
        ),
        migrations.AddField(
            model_name='netinterface',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.VM'),
        ),
    ]
