# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0012_auto_20161207_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netinterface',
            name='vm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='interface', to='Web.VM'),
        ),
    ]
