# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0014_auto_20161207_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netinterface',
            name='eth0_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eth0_vms', to='Web.Network'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='eth1_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eth1_vms', to='Web.Network'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='eth2_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eth2_vms', to='Web.Network'),
        ),
        migrations.AlterField(
            model_name='netinterface',
            name='eth3_network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eth3_vms', to='Web.Network'),
        ),
    ]
